#!/bin/bash
wg-quick up wg0
echo "Setting IP route table with given values for local network: $LOCAL_NETWORK"
# This will allow packages to be routed back to the local network, otherwise they will be routed trough wg0
# Creddit to https://github.com/trananhtuan
gw=$(ip route | awk '/default/ {print $3}')
ip route add to ${LOCAL_NETWORK} via $gw dev eth0
sockd